### ISSUE TITLE
USER STORY: Initial Django project setup

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#1]
As a **developer** I can **install the needed librarys and packages** so that **my project is set up correctly**

## Tasks
- [x] Task 1 - Install Django + Heroku server from command line
- [x] Task 2 - Install PostgreSql database from command line
- [x] Task 3 - Install Cloudinary from command line
- [x] Task 4 - Create requirements.txt file

**Comment by seanj06** [comment]
All librarys installed. Commit - [55d1095370](https://github.com/seanj06/MyCalorieCounter-P4/commit/55d1095370b85745525d66c06701ff7e00f72b42)
