### ISSUE TITLE
USER STORY: Connect Nutrition ApI

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#10]
As a **developer** I can **connect my project to an api** so that **users can search for info on thousands of different foods**

## Tasks
- [ ] Task 1 - Register for api-ninja account
- [ ] Task 2 - Copy api key and paste into views file
- [ ] Task 3 - Install requests from command line 
- [ ] Task 4 - Modify template to show api data
