### ISSUE TITLE
USER STORY: Create new django project and app

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#2]
As a **developer** I can **create a new Django project correcty** so that **my project can be built in the correct way**

## Tasks
- [x] Task 1 - Create new django project from command line
- [x] Task 2 - Create new app inside project andadd to installed apps on settings.py
- [x] Task 3 - Migrate all changes to database
- [x] Task 4 - Run app on server to make sure it was created successfully

**Comment by seanj06** [comment]
New Django Project and app created. Commit - [e27603365](https://github.com/seanj06/MyCalorieCounter-P4/commit/e27603365b0cfc8ab63dbcc8d8c954ff0c275c9b)
