### ISSUE TITLE
USER STORY: Get project ready for Heroku Deployment

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#3]
As a **developer** I can **deploy my project on Heroku** so that **it can be seen and used by other users**

## Tasks
- [x] Task 1 - Create new app on Heroku
- [x] Task 2 - Create new instance on ElephantSql dashboard
- [x] Task 3 - Create env.py file and change settings.py as required
- [x] Task 4 - Migrate changes to database
- [x] Task 5 - Add config vars on Heroku
- [x]  Task 6 - Create procfile
- [x] Task 7 - Deploy Branch in Heroku

**Comment by seanj06** [comment]
Deployment to heroku complete. Commit - [e27603365](https://github.com/seanj06/MyCalorieCounter-P4/commit/e27603365b0cfc8ab63dbcc8d8c954ff0c275c9b)
