### ISSUE TITLE
USER STORY: Create SuperUser for admin panel

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#4]
As a **developer** I can **create a superuser** so that **i can manage my application from the admin panel**

## Tasks
- [ ] Task 1 - Create Superuser from command line
- [ ] Task 2 - Install Summernote from command line
- [ ] Task 3 - Run project with /admin added to url to make sure superuser can login
