### ISSUE TITLE
USER STORY: Add Database Models

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#5]
As a **developer** I can **add database models** so that **the database knows how to handle user data**

## Tasks
- [ ] Task 1 - Import appropriate librarys at top of models.py file
- [ ] Task 2 - Create a class based model
- [ ] Task 3 - Add meta class to class based model
- [ ] Task 4 - MIgrate changes to database
