### ISSUE TITLE
USER STORY: Create Templates

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#7]
As a **developer** I can **create templates** so that **users can see the website online**

## Tasks
- [ ] Task 1 - Create templates folder
- [ ] Task 2 - Create base.html file to hold base template code
- [ ] Task 3 - Create base html template code
- [ ] Task 4 - Create news urls.py file and enter new path
