### ISSUE TITLE
USER STORY: Authentication

### ISSUE THREAD

**Issue by seanj06** [seanj06/MyCalorieCounter-P4#8]
As a **user** I can **create an account and log in** so that **I can track and save my progress**

## Tasks
- [ ] Task 1 - Install allauth using command line
- [ ] Task 2 - Hook up templates to allauth urls
- [ ] Task 3 - Customise templates
